import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastProvider } from "@/components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ToastProvider>
          {children}
        </ToastProvider>
        <footer className="border-t border-gray-800 mt-12 py-8 text-center text-gray-500 text-sm">
          <div className="flex justify-center gap-6 mb-4">
            <a href="/legal/terms" className="hover:text-white">Terms of Service</a>
            <a href="/legal/privacy" className="hover:text-white">Privacy Policy</a>
            <a href="https://github.com/bittune" className="hover:text-white">GitHub</a>
          </div>
          <p>© {new Date().getFullYear()} BitTune. Built with Nostr & Bitcoin.</p>
        </footer>
      </body>
    </html>
  );
}
